apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/instance: traefik-forward-auth
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: traefik-forward-auth
    app.kubernetes.io/version: 2.2.0
    helm.sh/chart: traefik-forward-auth-1.0.10
  name: traefik-forward-auth
---
apiVersion: v1
data:
  secret: R21Xc1ZpNGFxVGNrQXREaQ==
kind: Secret
metadata:
  labels:
    app.kubernetes.io/instance: traefik-forward-auth
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: traefik-forward-auth
    app.kubernetes.io/version: 2.2.0
    helm.sh/chart: traefik-forward-auth-1.0.10
  name: traefik-forward-auth
type: Opaque
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/instance: traefik-forward-auth
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: traefik-forward-auth
    app.kubernetes.io/version: 2.2.0
    helm.sh/chart: traefik-forward-auth-1.0.10
  name: traefik-forward-auth
spec:
  ports:
  - name: http
    port: 4181
    protocol: TCP
    targetPort: http
  selector:
    app.kubernetes.io/instance: traefik-forward-auth
    app.kubernetes.io/name: traefik-forward-auth
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/instance: traefik-forward-auth
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: traefik-forward-auth
    app.kubernetes.io/version: 2.2.0
    helm.sh/chart: traefik-forward-auth-1.0.10
  name: traefik-forward-auth
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/instance: traefik-forward-auth
      app.kubernetes.io/name: traefik-forward-auth
  template:
    metadata:
      labels:
        app.kubernetes.io/instance: traefik-forward-auth
        app.kubernetes.io/name: traefik-forward-auth
    spec:
      containers:
      - env:
        - name: SECRET
          valueFrom:
            secretKeyRef:
              key: secret
              name: traefik-forward-auth
        image: thomseddon/traefik-forward-auth:2.2.0
        imagePullPolicy: IfNotPresent
        livenessProbe:
          periodSeconds: 20
          tcpSocket:
            port: http
        name: traefik-forward-auth
        ports:
        - containerPort: 4181
          name: http
          protocol: TCP
        readinessProbe:
          periodSeconds: 10
          tcpSocket:
            port: http
      serviceAccountName: traefik-forward-auth
