---
# Source: traefik-forward-auth/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: traefik-forward-auth
  labels:
    helm.sh/chart: traefik-forward-auth-1.0.10
    app.kubernetes.io/name: traefik-forward-auth
    app.kubernetes.io/instance: traefik-forward-auth
    app.kubernetes.io/version: "2.2.0"
    app.kubernetes.io/managed-by: Helm
---
# Source: traefik-forward-auth/templates/secret.yaml
apiVersion: v1
kind: Secret
metadata:
  name: traefik-forward-auth
  labels:
    helm.sh/chart: traefik-forward-auth-1.0.10
    app.kubernetes.io/name: traefik-forward-auth
    app.kubernetes.io/instance: traefik-forward-auth
    app.kubernetes.io/version: "2.2.0"
    app.kubernetes.io/managed-by: Helm
type: Opaque
data:
  secret: "R21Xc1ZpNGFxVGNrQXREaQ=="
---
# Source: traefik-forward-auth/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: traefik-forward-auth
  labels:
    helm.sh/chart: traefik-forward-auth-1.0.10
    app.kubernetes.io/name: traefik-forward-auth
    app.kubernetes.io/instance: traefik-forward-auth
    app.kubernetes.io/version: "2.2.0"
    app.kubernetes.io/managed-by: Helm
spec:
  type: ClusterIP
  ports:
    - port: 4181
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: traefik-forward-auth
    app.kubernetes.io/instance: traefik-forward-auth
---
# Source: traefik-forward-auth/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: traefik-forward-auth
  labels:
    helm.sh/chart: traefik-forward-auth-1.0.10
    app.kubernetes.io/name: traefik-forward-auth
    app.kubernetes.io/instance: traefik-forward-auth
    app.kubernetes.io/version: "2.2.0"
    app.kubernetes.io/managed-by: Helm
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: traefik-forward-auth
      app.kubernetes.io/instance: traefik-forward-auth
  template:
    metadata:
      labels:
        app.kubernetes.io/name: traefik-forward-auth
        app.kubernetes.io/instance: traefik-forward-auth
    spec:
      serviceAccountName: traefik-forward-auth
      containers:
        - name: traefik-forward-auth
          image: "thomseddon/traefik-forward-auth:2.2.0"
          imagePullPolicy: IfNotPresent
          env:
            - name: SECRET
              valueFrom:
                secretKeyRef:
                  name: traefik-forward-auth
                  key: secret
          ports:
            - name: http
              containerPort: 4181
              protocol: TCP
          livenessProbe:
            periodSeconds: 20
            tcpSocket:
              port: http
          readinessProbe:
            periodSeconds: 10
            tcpSocket:
              port: http
